In [ ]:
import numpy as np # array creation, arry elements are seperated by white space

arr = np.array([10,20,30,40,50])
print(arr)
print(type(arr))

[10 20 30 40]
<class 'numpy.ndarray'>


In [2]:
l = [10,20,30]
print(l)
print(type(l)) # elemsta are sepearted by ,

[10, 20, 30]
<class 'list'>


In [4]:
arr = np.array([10, 1.1,20,30, "BLR"]) # if we try to create a array with dufferent datatype , it coverts the entire array to a higher data type array
print(arr)

['10' '1.1' '20' '30' 'BLR']


In [7]:
#Operations on Array

a1 = np.array([10,20,30])
print(a1)

a2 = a1+2


print(a2)

[10 20 30]
[12 22 32]


In [9]:
#Operations on List

a1 =[10,20,30]
print(a1)
a2 = a1*3
print(a2)

[10, 20, 30]
[10, 20, 30, 10, 20, 30, 10, 20, 30]


In [12]:
# memory consumption

import sys

l = [10,20,30]
print(sys.getsizeof(l))

a = np.array([10,20,30])
print(a.itemsize)
print(a.nbytes)

88
8
24


In [13]:
# creating ndarray

a = np.array([10,20,30,40])

print(a)
print(type(a))
print(a.ndim)

[10 20 30 40]
<class 'numpy.ndarray'>
1


In [14]:
#o dim array
a= np.array(44)
print(a)
print(type(a))
print(a.ndim)

44
<class 'numpy.ndarray'>
0


In [15]:
#2 dim array
a= np.array([[10,20,30]])
print(a)
print(type(a))
print(a.ndim)

[[10 20 30]]
<class 'numpy.ndarray'>
2


In [16]:
#2 dim array
a= np.array([[[10,20,30]]])
print(a)
print(type(a))
print(a.ndim)

[[[10 20 30]]]
<class 'numpy.ndarray'>
3


In [18]:
#n dimm array

n = int(input("enter the dim"))

a= np.array([10,20,30], ndmin=n)
print(a)
print(a.ndim)

enter the dim7
[[[[[[[10 20 30]]]]]]]
7


In [19]:
a = np.array([[10,20,30],[40,50,60]])
print(a)
print(a.ndim)

[[10 20 30]
 [40 50 60]]
2


In [27]:
a = np.array([[10,20,30],[40,50,60]])

print(a)

print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(a.nbytes)
print(a.min())
print(a.max())
print(a.sum())

print(a.sum(axis=0))
print(a.sum(axis=1))

print(a.mean())
print(a.std())
print(a.var())

[[10 20 30]
 [40 50 60]]
(2, 3)
6
int64
8
48
10
60
210
[50 70 90]
[ 60 150]
35.0
17.07825127659933
291.6666666666667


In [28]:
# create a nd array with all zeros

a = np.zeros(4)
print(a)
print(a.dtype)
print(a.ndim)
print(a.shape)

[0. 0. 0. 0.]
float64
1
(4,)


In [31]:
# create a nd array with all zeros

a = np.zeros((4,3), dtype='int')
print(a)
print(a.dtype)
print(a.ndim)
print(a.shape)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
int64
2
(4, 3)


In [32]:
# create a nd array with all zeros

a = np.ones((4,3), dtype='int')
print(a)
print(a.dtype)
print(a.ndim)
print(a.shape)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
int64
2
(4, 3)


In [34]:
# create a nd array with all zeros

a = np.ones((4,3), dtype='float') * 7
print(a)
print(a.dtype)
print(a.ndim)
print(a.shape)

[[7. 7. 7.]
 [7. 7. 7.]
 [7. 7. 7.]
 [7. 7. 7.]]
float64
2
(4, 3)


In [35]:
#arange function
a = np.arange(10)
print(a)
print(a.ndim)
print(a.shape)

[0 1 2 3 4 5 6 7 8 9]
1
(10,)


In [38]:
#arange function
a = np.arange(2,10,2,dtype = 'float')
print(a)
print(a.ndim)
print(a.shape)

[2. 4. 6. 8.]
1
(4,)


In [40]:

#linspace- generate numbers in linear space

a = np.linspace(1,2,5)
print(a)

[1.   1.25 1.5  1.75 2.  ]


In [41]:
# Create a 1D array using linspace
linear_space = np.linspace(1, 10, 12)  # Generates 12 numbers between 1 and 10

# Reshape the 1D array into a 2D array (e.g., 3 rows and 4 columns)
two_d_array = linear_space.reshape(3, 4)

print(two_d_array)

[[ 1.          1.81818182  2.63636364  3.45454545]
 [ 4.27272727  5.09090909  5.90909091  6.72727273]
 [ 7.54545455  8.36363636  9.18181818 10.        ]]


In [42]:
#Matrix

mat = np.matrix([[1,2,3],[4,5,6]])
print(mat)
print(type(mat))

[[1 2 3]
 [4 5 6]]
<class 'numpy.matrix'>


In [43]:
# transpose of a mtrix
mat = np.matrix([[1,2,3],[4,5,6]])
print(mat)

trans = mat.T
print(mat)
print(trans)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [45]:
# identity matrix

mat = np.identity(3)
print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [46]:
a = np.diag([10,20,30])
print(a)

[[10  0  0]
 [ 0 20  0]
 [ 0  0 30]]


In [47]:
# random numbers

a = np.random.random(10)
print(a)

[0.10981565 0.61255507 0.69165976 0.58706504 0.29290614 0.12693574
 0.07623645 0.83101348 0.98919298 0.29651471]


In [48]:
a = np.random.random((3,3,))
print(a)

[[0.68005548 0.43992827 0.15062832]
 [0.02683189 0.73178775 0.1087211 ]
 [0.91036725 0.30111957 0.16945403]]


In [60]:
r = np.random.randint(11,150, size =5)
print(r)

[142 118 143 104  83]


In [62]:
r = np.random.uniform(1,100, size=10)
print(r)

[89.2085604  57.91191596 99.78890461 81.07388874 67.17999009 93.85729551
 39.85608367 76.11054083 87.29562846 17.73468697]
