<a href="https://colab.research.google.com/github/richa-agarwal-de/python-machine-learning/blob/main/ML_LogisticRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression

In [3]:
diabetes_dataset = pd.read_csv('/content/diabetes.csv')

In [5]:
diabetes_dataset.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [8]:
diabetes_dataset.shape

(768, 9)

In [10]:
diabetes_dataset.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [11]:
diabetes_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [13]:
diabetes_dataset['Outcome'].value_counts()  ## as outcome is unbalanced, it can cause biased model

Outcome
0    500
1    268
Name: count, dtype: int64

## separating the features and target

In [22]:
features = diabetes_dataset.drop(columns='Outcome',axis=1)
features.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

In [23]:
target = diabetes_dataset['Outcome']
target.head()

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

## Standardise values to a similar range.

In [24]:
from sklearn.preprocessing import StandardScaler

In [25]:
scaler = StandardScaler()

#### Below fit and transform can be done in one step using fit and transform

In [26]:
scaler.fit(features)

StandardScaler()

In [28]:
standardized_data = scaler.transform(features)

In [30]:
standardized_data

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [31]:
features = standardized_data

## Split data into training and testing data set

In [32]:
from sklearn.model_selection import train_test_split

In [33]:
x_train, x_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=2)

In [34]:
x_test

array([[-0.54791859, -1.02950492,  0.25303625, ..., -0.37981576,
        -0.73351526, -0.95646168],
       [-0.54791859,  0.25367803,  0.77001375, ..., -0.506735  ,
        -0.56740873, -0.53102292],
       [-1.14185152, -0.59134489,  0.45982725, ...,  0.31824009,
        -0.70633419, -0.78628618],
       ...,
       [-1.14185152,  0.34756947,  0.45982725, ...,  0.05170968,
        -0.23821579, -1.04154944],
       [ 0.3429808 ,  0.5040552 ,  2.01075975, ...,  2.1331853 ,
        -0.73955549,  0.31985461],
       [-0.84488505, -1.4989621 , -0.98770975, ..., -1.14133123,
        -0.676133  , -1.04154944]])

In [36]:
print(features.shape, x_train.shape, x_test.shape)

(768, 8) (614, 8) (154, 8)


## Training the model

In [37]:
classifier = LogisticRegression(random_state=0, max_iter=1000)

In [38]:
classifier.fit(x_train,y_train)

LogisticRegression(max_iter=1000, random_state=0)

In [39]:
y_prediction = classifier.predict(x_test)

## Check for the accuracy of generated model

In [42]:
from sklearn.metrics import accuracy_score

In [43]:
test_accuracy = accuracy_score(y_test,y_prediction)

In [44]:
print(test_accuracy)

0.7662337662337663


## Testing the model

In [48]:
input_data = (5,166,72,19,175,25.8,0.58,51)
input_data

(5, 166, 72, 19, 175, 25.8, 0.58, 51)

In [49]:
# converting tuple to np array format
input_data_arrayformat = np.asarray(input_data)
input_data_arrayformat

array([  5.  , 166.  ,  72.  ,  19.  , 175.  ,  25.8 ,   0.58,  51.  ])

In [50]:
# Reshape the data
input_data_reshaped = input_data_arrayformat.reshape(1,-1)
input_data_reshaped

array([[  5.  , 166.  ,  72.  ,  19.  , 175.  ,  25.8 ,   0.58,  51.  ]])

In [52]:
#transform the data
std_data = scaler.transform(input_data_reshaped)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [53]:
std_data

array([[ 0.3429808 ,  1.41167241,  0.14964075, -0.09637905,  0.82661621,
        -0.78595734,  0.3265464 ,  1.51108316]])

In [54]:
# predict the outcome
prediction = classifier.predict(std_data)

if (prediction==0):
  print('The person is not diabetic')
else:
  print('The person is diabetic')

The person is diabetic
