<a href="https://colab.research.google.com/github/richa-agarwal-de/python-machine-learning/blob/main/Python_M4_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Array

## List vs Numpy Array
### numpy elements separated by space ' '. List elements separated by comma ','
### List can have elements of different data types. Numpy array elements should be of same datatype

In [2]:
import numpy as np

In [ ]:
## Create numpy array

arr = np.array([10,20,30,40])
print(arr)
print(type(arr))

[10 20 30 40]
<class 'numpy.ndarray'>


In [ ]:
## List

l = [10,20,30,40]
print(l)
print(type(l))

[10, 20, 30, 40]
<class 'list'>


In [ ]:
arr1 = np.array([10,20,30.8])
print(arr1)
print(type(arr1))

[10.  20.  30.8]
<class 'numpy.ndarray'>


In [ ]:
arr2 = np.array([10,'Blr',13.0,20]) ## Python internally converts the datatype of the elements to the higher datatype when array is defined with different data types
print(arr2)
print(type(arr2))

['10' 'Blr' '13.0' '20']
<class 'numpy.ndarray'>


In [3]:
#n dimm array

n = int(input("enter the dim"))

a= np.array([10,20,30], ndmin=n)
print(a)
print(a.ndim)

enter the dim5
[[[[[10 20 30]]]]]
5


# Day 2 below. Yet to complete day 1 code above

In [4]:
## choice - pick random numbers from the given list

k = np.random.choice([10,20,30,40,50],size = 3) # this can output duplicate valuesin the array as well
print(k)

[50 20 50]


In [6]:
## choice - pick random numbers from the given list without duplicates

k = np.random.choice([10,20,30,40,50],size = 3, replace= False) #replace default is True thats why it generates duplicates. to remove duplicates use replace = False.
print(k)

[10 50 30]


In [14]:
## choice with probability

a = np.array([22,33,44])
probability = np.array([.5,.1,.4]) # sum of all probability should be 1

k = np.random.choice(a, p=probability,size=10)
print(k)

[44 44 22 44 44 33 44 44 33 22]


In [46]:
## Choosing random rows

arr_2d = np.arange(0,20).reshape(4,5)
print(arr_2d)

rowno = arr_2d.shape[0]
colno = arr_2d.shape[1]
print(rowno)
print(colno)

random_rowindex = np.random.choice(rowno,size=2, replace=False)
print(random_rowindex)

random_colindex = np.random.choice(colno,size=2,replace=False)
print(random_colindex)

final_output_rows = arr_2d[random_rowindex]
print(final_output_rows)

final_output_cols = arr_2d[:,random_colindex]
print(final_output_cols)


final_output = arr_2d[random_rowindex][:,random_colindex]
print(final_output)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
4
5
[3 0]
[2 1]
[[15 16 17 18 19]
 [ 0  1  2  3  4]]
[[ 2  1]
 [ 7  6]
 [12 11]
 [17 16]]
[[17 16]
 [ 2  1]]


In [50]:
## shuffling the array

a = np.arange(0,12).reshape(3,4)
print(a)

np.random.shuffle(a)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


#### shuffle vs permutation:
- shuffle changes array in place
- permutation generates new array. original array remains same

In [54]:
# permutation - generate shuffled array

a = np.random.permutation(12)
print(a)


[ 7  1  6  2  4 10  8  9 11  3  5  0]


In [55]:
# permutation - 2d array

a = np.random.permutation(12).reshape(3,4)
print(a)

[[ 2  6  1  7]
 [11  4  8  5]
 [ 3 10  0  9]]


In [56]:
# permnutaion 2d array

arr_2d = np.arange(12).reshape(3,4)
print(arr_2d)

perm_arr = np.random.permutation(arr_2d)
print(perm_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]


In [61]:


arr_2d = np.arange(0,20).reshape(4,5)
print(arr_2d)

num_rows = arr_2d.shape[0]
print(num_rows)

shuffled_index = np.random.permutation(num_rows)
print(shuffled_index)

shuffled_array = arr_2d[shuffled_index]

print(shuffled_array)

num_cols = arr_2d.shape[1]
print(num_cols)

shuffled_index_col = np.random.permutation(num_cols)

shuffled_array_col = arr_2d[:,shuffled_index_col]
print(shuffled_array_col)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
4
[2 3 0 1]
[[10 11 12 13 14]
 [15 16 17 18 19]
 [ 0  1  2  3  4]
 [ 5  6  7  8  9]]
5
[[ 1  4  3  2  0]
 [ 6  9  8  7  5]
 [11 14 13 12 10]
 [16 19 18 17 15]]


### grouping and splitting

In [64]:
arr_1d = np.arange(10)
print(arr_1d)

arr_2d_0 = np.arange(0,18).reshape(3,6)
print(arr_2d_0)

arr_2d_1 = np.arange(18,36).reshape(3,6)
print(arr_2d_1)



[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[[18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [67]:
## concatenate

a = np.concatenate([arr_2d_0,arr_2d_1]) # default concatenation row wise or axis = 0
print(a)


b = np.concatenate([arr_2d_0,arr_2d_1],axis=1) # to concatenate column wise or axis = 1
print(b)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[[ 0  1  2  3  4  5 18 19 20 21 22 23]
 [ 6  7  8  9 10 11 24 25 26 27 28 29]
 [12 13 14 15 16 17 30 31 32 33 34 35]]


In [69]:
## np stack or numpy stack

a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

print(np.stack([a1,a2]))

print(np.stack([a1,a2],axis=1))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [74]:
## stacking 2d array

arr_2d_0 = np.arange(0,18).reshape(3,6)
print(arr_2d_0)
print('\n****************\n')
arr_2d_1 = np.arange(18,36).reshape(3,6)
print(arr_2d_1)
print('\n****************\n')

sarr_0 = np.stack([arr_2d_0,arr_2d_1],axis=0)
print(sarr_0)
print(sarr_0.shape)
print('\n****************\n')

sarr_1 = np.stack([arr_2d_0,arr_2d_1],axis=1)
print(sarr_1)
print(sarr_1.shape)
print('\n****************\n')

sarr_2 = np.stack([arr_2d_0,arr_2d_1],axis=2)
print(sarr_2)
print(sarr_2.shape)
print('\n****************\n')


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]

****************

[[18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

****************

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]]

 [[18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]]
(2, 3, 6)

****************

[[[ 0  1  2  3  4  5]
  [18 19 20 21 22 23]]

 [[ 6  7  8  9 10 11]
  [24 25 26 27 28 29]]

 [[12 13 14 15 16 17]
  [30 31 32 33 34 35]]]
(3, 2, 6)

****************

[[[ 0 18]
  [ 1 19]
  [ 2 20]
  [ 3 21]
  [ 4 22]
  [ 5 23]]

 [[ 6 24]
  [ 7 25]
  [ 8 26]
  [ 9 27]
  [10 28]
  [11 29]]

 [[12 30]
  [13 31]
  [14 32]
  [15 33]
  [16 34]
  [17 35]]]
(3, 6, 2)

****************



In [75]:
# vertical stacking

np.vstack([arr_2d_0,arr_2d_1]) # np.concatenate axis = 0


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [77]:
# horizontal stacking

np.hstack([arr_2d_0,arr_2d_1]) # np.concatenate axis = 1

array([[ 0,  1,  2,  3,  4,  5, 18, 19, 20, 21, 22, 23],
       [ 6,  7,  8,  9, 10, 11, 24, 25, 26, 27, 28, 29],
       [12, 13, 14, 15, 16, 17, 30, 31, 32, 33, 34, 35]])

In [83]:
# splitting 1d array

arr_1d = np.arange(10)
print(arr_1d)

k = np.split(arr_1d,indices_or_sections=5)

print(k)
print(k[3])

print(type(k))
print(type(k[3]))

[0 1 2 3 4 5 6 7 8 9]
[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]
[6 7]
<class 'list'>
<class 'numpy.ndarray'>


In [84]:
# split 2d array

print(arr_2d_0)

k = np.split(arr_2d_0,indices_or_sections=3,axis=0)
print(k)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17]])]


In [85]:
# split 2d array

print(arr_2d_0)

k = np.split(arr_2d_0,indices_or_sections=3,axis=1)
print(k)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([[ 4,  5],
       [10, 11],
       [16, 17]])]


In [87]:
## expanding dimensions -- addiing axis

print(arr_2d_0)
print(arr_2d_0.ndim)
print(arr_2d_0.shape)


new_array = np.expand_dims(arr_2d_0, axis=0)
print(new_array)
print(new_array.ndim)
print(new_array.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
2
(3, 6)
[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]]]
3
(1, 3, 6)


In [88]:
## squeeze

k = np.squeeze(new_array)
print(k)
print(k.shape)
print(k.ndim)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
(3, 6)
2


In [89]:
# reordering

## flip

arr_1d = np.arange(10)

print(arr_1d)
print(np.flip(arr_1d))

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


In [94]:
arr_2d = np.arange(10).reshape(2,5)

print(arr_2d)
print('\n****************\n')
print(np.flip(arr_2d))
print('\n****************\n')
print(np.flip(arr_2d,axis=0))
print('\n****************\n')
print(np.flip(arr_2d,axis=1))

[[0 1 2 3 4]
 [5 6 7 8 9]]

****************

[[9 8 7 6 5]
 [4 3 2 1 0]]

****************

[[5 6 7 8 9]
 [0 1 2 3 4]]

****************

[[4 3 2 1 0]
 [9 8 7 6 5]]


In [102]:
# resize

print(arr_2d)
print('\n****************\n')
print(np.resize(arr_2d, new_shape=8))
print('\n****************\n')
print(np.resize(arr_2d,new_shape=(4,2)))

print('\n****************\n')
print(np.resize(arr_2d,new_shape=(4,4))) #if  new arr elements more than provided array elements, it repeats the array

print('\n****************\n')
print(arr_2d.reshape(5,2))



[[0 1 2 3 4]
 [5 6 7 8 9]]

****************

[0 1 2 3 4 5 6 7]

****************

[[0 1]
 [2 3]
 [4 5]
 [6 7]]

****************

[[0 1 2 3]
 [4 5 6 7]
 [8 9 0 1]
 [2 3 4 5]]

****************

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
