# Numpy Array

## List vs Numpy Array
### numpy elements separated by space ' '. List elements separated by comma ','
### List can have elements of different data types. Numpy array elements should be of same datatype

In [1]:
import numpy as np

In [4]:
## Create numpy array

arr = np.array([10,20,30,40])
print(arr)
print(type(arr))

[10 20 30 40]
<class 'numpy.ndarray'>


In [5]:
## List

l = [10,20,30,40]
print(l)
print(type(l))

[10, 20, 30, 40]
<class 'list'>


In [6]:
arr1 = np.array([10,20,30.8])
print(arr1)
print(type(arr1))

[10.  20.  30.8]
<class 'numpy.ndarray'>


In [7]:
arr2 = np.array([10,'Blr',13.0,20]) ## Python internally converts the datatype of the elements to the higher datatype when array is defined with different data types
print(arr2)
print(type(arr2))

['10' 'Blr' '13.0' '20']
<class 'numpy.ndarray'>


In [8]:
#n dimm array

n = int(input("enter the dim"))

a= np.array([10,20,30], ndmin=n)
print(a)
print(a.ndim)

enter the dim7
[[[[[[[10 20 30]]]]]]]
7
